Algoritmo "Dobro"
//  
//  
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 20/01/2023
Var
n1,  mult : real



Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
 Escreva ("ESCREVA UM NUMERO: ")
 Leia (n1)
     mult <- n1 * 2
     
 Escreva (" O dobro de:", n1," é =", mult)
 

Fimalgoritmo