Algoritmo "semnome"

Var
anoA, anoN, idade:real



Inicio

Escreva ("Me informe seu ano de nascimento: ")
Leia (anoN)
Escreva ("E o ano que nós estamos: ")
Leia (anoA)

idade <- anoA - anoN
EscrevaL ("Sua idade é:", idade)

SE idade >= 21 entao
Escreva ("Se você tem", idade, " anos já atingiu a maioridade")
SENAO
Escreva ("Você ainda é menor de idade")
FIMSE








Fimalgoritmo