Algoritmo "menos"
//  
//  
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 20/01/2023
Var
n3, n4, subtracao: inteiro

Inicio

Escreva ("DIGITE UM NÚMERO: ")
Leia (n3)
EscrevaL
Escreva ("DIGITE OUTRO NÚMERO: ")
Leia (n4)
EscrevaL
       subtracao <- n3 - n4

 Escreva (" A subtracao entre", n3, " -", n4, " é =", subtracao)

Fimalgoritmo