Algoritmo "Soma"
//  
//  

//  SOLICITAR DOIS NÚMEROS PARA O USUÁRIO E MOSTRAR A SOMA ENTRE ELES

Var

n1, n2, soma: inteiro


Inicio
   Escreva ("DIGITE UM NÚMERO: ")
   Leia (n1)
   Escreva ("DIGITE OUTRO NÚMERO: ")
   Leia (n2)
   
   Soma <- n1+n2
   
   EscrevaL ("A soma entre os dois números: ", soma)
   Escreva (" A soma entre", n1, " +", n2, " é = ", soma)
   
   
   
   

Fimalgoritmo